### ISSUE TITLE
Repetitive folders in models directory

### ISSUE THREAD

**Issue by KubraE** [jbohnslav/deepethogram#28] opened 2020-12-01 05:14 UTC
Hi,

I followed the steps in "getting_started.md" one by one. After that, in my models directory there were some folders with the same name(except the time stamps) like the examples below. I just wanted to make sure I am on the right track, so I wanted to ask what can be the reason for it and is this normal? If yes, which one should be used for next steps? 

<img width="442" alt="Screen Shot 2020-11-30 at 5 23 48 PM" src="https://user-images.githubusercontent.com/34382537/100699071-034e2380-3368-11eb-9fb1-0ded71cd04b2.png">
<img width="523" alt="Screen Shot 2020-11-30 at 5 24 08 PM" src="https://user-images.githubusercontent.com/34382537/100699099-13660300-3368-11eb-97f1-7521ae2c48fb.png">
<img width="494" alt="Screen Shot 2020-11-30 at 5 23 01 PM" src="https://user-images.githubusercontent.com/34382537/100699149-385a7600-3368-11eb-86b2-122bc3115f55.png">

**Comment by jbohnslav** [comment] 2020-12-01 13:15
Hi Kubra, yes these are exactly as intended. Each of these is from a different model you trained. Looking good! 

Some tips: 
* If nothing went wrong with inference, you can delete those. It's not a large folder, but it can make your model directory cleaner. 
* If you trained multiple models, you can open up `opticalflow_metrics.tiff` and see which model has lower validation loss (the other metrics and figures will be informative as well). You can delete the ones with worse performance. 
* However, if you added data between model runs, it's best to keep the one with the most data in most cases

**Closed by jbohnslav** 2020-12-01 13:15 UTC
